---
title: "citations_merging_ajps_apsr"
author: "Teresita Cruz and Ravina Pattni"
date: "April 21, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
knitr::opts_chunk$set(echo = TRUE)
```
 
Article Topic and Type 
```{r}
ajps_type_topic <- read.csv("../../URAPshared/Data/ajps_article_coding_harmonized.csv")

apsr_type_topic <- read.csv("../../URAPshared/Data/apsr_article_coding_harmonized.csv")

main.df <- bind_rows(ajps_type_topic, apsr_type_topic)

#changing levels
topic_levels <- c("political_theory","american_government_and_politics",
                  "political_methodology","international_relations",
                  "comparative_politics")

main.df$article_topic1 <- factor(main.df$article_topic1, levels = topic_levels)

data_type_levels <- c("experimental", "observational", "simulations", "")

main.df$article_data_type <- factor(main.df$article_data_type)

```

Author Website Coding
```{r}
ajps_author_website <- read.csv("../../URAPshared/Data/ajps_author_website_coding_harmonized.csv")
apsr_author_website <- read.csv("../../URAPshared/Data/apsr_author_website_coding_harmonized.csv")

# # # ##author_web <- bind_rows(ajps_author_website, apsr_author_website)

# # # AJPS
ajps_web <- ajps_author_website %>%
  mutate(data.avail = ajps_author_website$website_category == "data",
         code.avail = ajps_author_website$website_category == "code",
         files.avail = ajps_author_website$website_category == "files")

ajps_web$data.avail <- as.numeric(ajps_web$data.avail)
ajps_web$code.avail <- as.numeric(ajps_web$code.avail)
ajps_web$files.avail <- as.numeric(ajps_web$files.avail)


ajps_web <- ajps_web %>%
  group_by(doi) %>%
  summarize(data_web = max(data.avail),
            code_web = max(code.avail),
            files_web = max(files.avail))

# # # # # APSR 
apsr_web <- apsr_author_website %>%
  mutate(data.avail = apsr_author_website$website_category == "data",
         code.avail = apsr_author_website$website_category == "code",
         files.avail = apsr_author_website$website_category == "files")

aps_rweb$data.avail <- as.numeric(apsr_web$data.avail)
apsr_web$code.avail <- as.numeric(apsr_web$code.avail)
apsr_web$files.avail <- as.numeric(apsr_web$files.avail)

apsr_web_sum <- apsr_web %>%
  group_by(doi) %>%
  summarize(title = first(title),
            data_web = max(data.avail),
            code_web = max(code.avail),
            files_web = max(files.avail)) %>%
  anti_join(apsr_type_topic, by='doi') %>% View()

## checking for "extra" articles in test_apsrweb with apsr_type_topic by doi 
apsr_diff <- anti_join(apsr_web_sum, apsr_type_topic, by = "doi")


# DO NOT RUN
# adding data, code and files availability to the main data frame
main.df <- right_join(main.df, author_web_data, by = "doi")


# this was an erratum on an erratum == "files" were available for the paper, but this here was 
# a clarification on that paper. 
main.df <- mutate(main.df, files_web = replace(files_web, doi == "10.1111/j.1540-5907.2011.00554.x", "skip"))

# if files = 1 then data & code = 1 ,
main.df$data_web[main.df$files_web == 1] <- "1"

main.df$code_web[main.df$files_web == 1] <- "1"

# for obs. where data was available from one author and code from another, files=1
main.df$files_web[main.df$data_web == 1 & main.df$code_web ==1] <- "1"


```

Dataverse 
```{r}
ajps_dataverse <- read.csv("../../URAPshared/Data/ajps_dataverse_diff_resolution_RP_TC.csv")

apsr_dataverse <- read.csv("../../URAPshared/Data/apsr_dataverse_diff_resolution_RP_TC.csv")

# bind ajps and apsr dataverse file and add dataverse variable to main df
dataverse <- bind_rows(ajps_dataverse, apsr_dataverse)

#made result_category_RP_TC_resolved a factor variable so that we could then 
#individual vars for files, data, and code availability on dataverse
dataverse$result_category_RP_TC_resolved <- as.factor(dataverse$result_category_RP_TC_resolved)

dataverse <- dataverse %>% 
  mutate(files_dataverse = dataverse$result_category_RP_TC_resolved == "files",
         data_dataverse = dataverse$result_category_RP_TC_resolved == "data",
         code_dataverse = dataverse$result_category_RP_TC_resolved == "code")
  
dataverse$files_dataverse <- as.numeric(dataverse$files_dataverse)
dataverse$data_dataverse <- as.numeric(dataverse$data_dataverse)
dataverse$code_dataverse <- as.numeric(dataverse$code_dataverse)

# "collapse" dataverse file so that there is only one obs. per article 
dataverse1 <- dataverse %>%
  group_by(doi) %>%
  summarize(files_dataverse = max(files_dataverse),
            data_dataverse = max(data_dataverse),
            code_dataverse = max(code_dataverse))

# add files, data and code dataverse variables to the main df
main.df <- left_join(main.df, dataverse1, by="doi")

# if files_dataverse=1 then data_dataverse and code_dataverse =1
main.df$data_dataverse[main.df$files_dataverse == 1] <- "1"
main.df$code_dataverse[main.df$files_dataverse == 1] <- "1"


```

Links 
```{r}
# uploading and binding ajps and apsr links
ajps_links <- read.csv("../../URAPshared/Data/ajps_link_coding_diff_resolution.csv")

apsr_links <- read.csv("../../URAPshared/Data/apsr_link_coding_RP.csv")

links <- bind_rows(ajps_links, apsr_links)

# create variables: files_link, data_link and code_link. Note: only consider full file, data and code
links <- links %>% 
  mutate(files_link = links$link_category_resolved == "files",
         data_link = links$link_category_resolved == "data",
         code_link = links$link_category_resolved == "code")

links$files_link <- as.numeric(links$files_link)
links$data_link <- as.numeric(links$data_link)
links$code_link <- as.numeric(links$code_link)

links <- links %>%
  group_by(doi) %>%
  summarize(files_link = max(files_link),
            data_link = max(data_link),
            code_link = max(code_link))

# If files = 1 then data = 1 and code = 1
links$data_link[links$files_link == 1] <- "1"
links$code_link[links$files_link == 1] <- "1"

# If data = 1 and code = 1 then files = 1
links$files_link[links$data_link == 1 & links$code_link == 1] <- "1"

# Make files_link, data_link and code_link numeric
links$files_link <- as.numeric(links$files_link)
links$data_link <- as.numeric(links$data_link)
links$code_link <- as.numeric(links$code_link)

# Append links to main.df
main.df <- left_join(main.df, links, by="doi")

```


Reference Coding
```{r}
# # # # # Reference Coding 
ajps_references <- read.csv("../../URAPshared/Data/ajps_reference_coding_harmonized.csv")
apsr_references <- read.csv("../../URAPshared/Data/apsr_reference_coding_harmonized.csv")

references <- bind_rows(ajps_references, apsr_references)

references <- references %>%
  mutate(files_full_name = reference_category == "files_full_name",
            data_full_name = reference_category == "data_full_name",
            code_full_name = reference_category == "code_full_name")

references$files_full_name <- as.numeric(references$files_full_name)
references$data_full_name <- as.numeric(references$data_full_name)
references$code_full_name <- as.numeric(references$code_full_name)

ref <- references %>%
  group_by(doi) %>%
  summarise(files_references = max(files_full_name),
            data_references = max(data_full_name),
            code_references = max(code_full_name))

```

Reference CHECK
```{r}
# # # # Reference coding check
ajps_references <- read.csv("../../URAPshared/Data/ajps_reference_coding_harmonized.csv")
apsr_references <- read.csv("../../URAPshared/Data/apsr_reference_coding_harmonized.csv")

ajps_references <- ajps_references %>%
  mutate(files_full_name = reference_category == "files_full_name",
         data_full_name = reference_category == "data_full_name",
         code_full_name = reference_category == "code_full_name")

ajps_references$files_full_name <- as.numeric(ajps_references$files_full_name)
ajps_references$data_full_name <- as.numeric(ajps_references$data_full_name)
ajps_references$code_full_name <- as.numeric(ajps_references$code_full_name)

test_ajpsref <- ajps_references %>%
  group_by(doi) %>%
  summarise(files_references = max(files_full_name),
            data_references = max(data_full_name),
            code_references = max(code_full_name))

apsr_references <- apsr_references %>%
  mutate(files_full_name = reference_category == "files_full_name",
         data_full_name = reference_category == "data_full_name",
         code_full_name = reference_category == "code_full_name")

apsr_references$files_full_name <- as.numeric(apsr_references$files_full_name)
apsr_references$data_full_name <- as.numeric(apsr_references$data_full_name)
apsr_references$code_full_name <- as.numeric(apsr_references$code_full_name)

test_apsrref <- apsr_references %>%
  group_by(doi) %>%
  summarise(files_references = max(files_full_name),
            data_references = max(data_full_name),
            code_references = max(code_full_name))


###### TEST FOR EACH MERGER ##########
anti_join(dv, main, by = 'doi') %>% nrows




```
Adding volume,issue, pulbication date, author, author affiliation columns to the main dataframe
```{r}
apsr_template <- read.csv("../../URAPshared/Data/apsr_reference_coding_template.csv")

apsr_template <- apsr_template %>%
  select(volume, issue, pages, publication_date, doi) %>%
  distinct

main.df <- right_join(main.df, apsr_template, by = "doi")

ajps_template <- read.csv("../../URAPshared/Data/ajps_article_info_from_issue_toc.csv")

ajps_template <- ajps_template %>%
  select(issue_number,issue_pages, doi) %>%
  distinct

main.df <- right_join(main.df, ajps_template, by="doi")

```
Apsr centennial issue - references
```{r}
apsr_centennial_ref <- read.csv("../../URAPshared/Data/..")

apsr_centennial_ref <- apsr_centennial_ref %>%
  mutate(files_full_name = reference_category == "files_full_name",
         data_full_name = reference_category == "data_full_name",
         code_full_name = reference_category == "code_full_name")

apsr_centennial_ref$files_full_name <- as.numeric(apsr_centennial_ref$files_full_name)
apsr_centennial_ref$data_full_name <- as.numeric(apsr_centennial_ref$data_full_name)
apsr_centennial_ref$code_full_name <- as.numeric(apsr_centennial_ref$code_full_name)

apsr_centennial_ref <- apsr_centennial_ref %>%
  group_by(doi) %>%
  summarise(files_references = max(files_full_name),
            data_references = max(data_full_name),
            code_references = max(code_full_name))

main.df <- left_join(main.df, apsr_centennial_ref, by="doi")

```
Apsr centennial issue - links
```{r}
# uploading and binding apsr centennial links

apsr_cent_links <- read.csv("../../URAPshared/Data/..")

# create variables: files_link, data_link and code_link. Note: only consider full file, data and code
apsr_cent_links <- apsr_cent_links %>% 
  mutate(files_link = apsr_cent_links$link_category_resolved == "files",
         data_link = apsr_cent_links$link_category_resolved == "data",
         code_link = apsr_cent_links$link_category_resolved == "code")

apsr_cent_links$files_link <- as.numeric(apsr_cent_links$files_link)
apsr_cent_links$data_link <- as.numeric(apsr_cent_links$data_link)
apsr_cent_links$code_link <- as.numeric(apsr_cent_links$code_link)

apsr_cent_links <- apsr_cent_links %>%
  group_by(doi) %>%
  summarize(files_link = max(files_link),
            data_link = max(data_link),
            code_link = max(code_link))

# If files = 1 then data = 1 and code = 1
apsr_cent_links$data_link[apsr_cent_links$files_link == 1] <- "1"
apsr_cent_links$code_link[apsr_cent_links$files_link == 1] <- "1"

# If data = 1 and code = 1 then files = 1
apsr_cent_links$files_link[apsr_cent_links$data_link == 1 & apsr_cent_links$code_link == 1] <- "1"

# Make files_link, data_link and code_link numeric
apsr_cent_links$files_link <- as.numeric(apsr_cent_links$files_link)
apsr_cent_links$data_link <- as.numeric(apsr_cent_links$data_link)
apsr_cent_links$code_link <- as.numeric(apsr_cent_links$code_link)

# Append centennial links to main.df
main.df <- left_join(main.df, apsr_cent_links, by="doi")

```
Apsr centennial article topic and type
```{r}
apsr_cent_topic_type <- read.csv("../../URAPshared/Data/")


#changing levels
topic_levels1 <- c("political_theory","american_government_and_politics",
                  "political_methodology","international_relations",
                  "comparative_politics")

main.df$article_topic <- factor(main.df$article_topic, levels = topic_levels)

data_type_levels1 <- c("experimental", "observational", "simulations", "")

main.df$article_data_type1 <- factor(main.df$article_data_type1)
```
